import {
  FaRocket, FaBuilding, FaGraduationCap, FaShoppingCart,
  FaBullhorn, FaUsers, FaHeartbeat, FaCalendarAlt,
  FaUtensils, FaTicketAlt,
  FaServer, FaMobileAlt, FaBrain, FaCloud, FaPenFancy,
  FaCogs, FaChartLine, FaShieldAlt, FaBolt,
  FaStar, FaGlobeAmericas, FaClock, FaCode,
} from "react-icons/fa";

export const industryData = [
  {
    id: "startup",
    title: "Business Startup",
    subtitle: "Launch your startup with confidence",
    icon: <FaRocket />,
    color: "#4F7DFF",
    description: "We help entrepreneurs transform innovative ideas into successful businesses through technology, branding, and strategic planning. From MVP development to full-scale launch, we provide end-to-end support.",
    badge: "Fast Track",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Startups Delivered", value: 250, suffix: "+", icon: <FaRocket /> },
      { label: "Client Satisfaction", value: 98, suffix: "%", icon: <FaStar /> },
      { label: "Countries Served", value: 20, suffix: "+", icon: <FaGlobeAmericas /> },
      { label: "Uptime Guarantee", value: 99.9, suffix: "%", icon: <FaClock /> },
    ],
    features: ["Startup Strategy Planning", "MVP Development", "Business Automation", "Cloud Integration", "Technology Consulting"],
    benefits: ["Faster Market Entry", "Lower Development Cost", "Scalable Infrastructure", "Improved Brand Presence", "Better Customer Acquisition"],
  },
  {
    id: "enterprise",
    title: "Enterprise Service",
    subtitle: "Robust, scalable enterprise solutions",
    icon: <FaBuilding />,
    color: "#8B5CF6",
    description: "Enterprise solutions designed to streamline operations, improve efficiency, and support large-scale business growth with cutting-edge technology infrastructure.",
    badge: "Enterprise Grade",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Enterprise Clients", value: 180, suffix: "+", icon: <FaBuilding /> },
      { label: "System Uptime", value: 99.99, suffix: "%", icon: <FaShieldAlt /> },
      { label: "Data Processed", value: 50, suffix: "TB+", icon: <FaServer /> },
      { label: "Global Offices", value: 12, suffix: "", icon: <FaGlobeAmericas /> },
    ],
    features: ["ERP Integration", "CRM Solutions", "Cloud Infrastructure", "Business Intelligence", "Data Analytics"],
    benefits: ["Improved Productivity", "Centralized Operations", "Better Decision Making", "Enhanced Security", "Reduced Operational Costs"],
  },
  {
    id: "education",
    title: "Education & Learning",
    subtitle: "Smart solutions for smart learners",
    icon: <FaGraduationCap />,
    color: "#22D3EE",
    description: "Modern educational platforms that enhance online learning experiences for students, teachers, and institutions with AI-powered personalization.",
    badge: "EdTech",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Students Reached", value: 50000, suffix: "+", icon: <FaGraduationCap /> },
      { label: "Courses Built", value: 1200, suffix: "+", icon: <FaStar /> },
      { label: "Active Schools", value: 350, suffix: "+", icon: <FaBuilding /> },
      { label: "Countries", value: 15, suffix: "+", icon: <FaGlobeAmericas /> },
    ],
    features: ["E-Learning Platforms", "Student Management", "Live Classes", "Online Assessments", "Learning Analytics"],
    benefits: ["Better Student Engagement", "Remote Learning Support", "Improved Learning Outcomes", "Easy Administration", "Scalable Education Systems"],
  },
  {
    id: "ecommerce",
    title: "Ecommerce & Retail",
    subtitle: "Scalable retail solutions",
    icon: <FaShoppingCart />,
    color: "#F59E0B",
    description: "Comprehensive ecommerce platforms that help businesses sell products online and manage operations efficiently with powerful analytics.",
    badge: "Revenue Boost",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Stores Launched", value: 320, suffix: "+", icon: <FaShoppingCart /> },
      { label: "Revenue Generated", value: 50, suffix: "Cr+", icon: <FaChartLine /> },
      { label: "Products Listed", value: 100000, suffix: "+", icon: <FaStar /> },
      { label: "Monthly Traffic", value: 2, suffix: "M+", icon: <FaGlobeAmericas /> },
    ],
    features: ["Online Store Setup", "Payment Gateway Integration", "Inventory Management", "Order Tracking", "Customer Dashboard"],
    benefits: ["Increased Sales", "Global Reach", "Improved Customer Experience", "Easy Inventory Control", "Higher Revenue"],
  },
  {
    id: "cybersecurity",
    title: "Cyber Security",
    subtitle: "Protect your digital assets",
    icon: <FaShieldAlt />,
    color: "#059669",
    description: "Comprehensive cybersecurity services to protect your business from evolving threats with advanced security monitoring, incident response, and compliance management.",
    badge: "Secure & Compliant",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Threats Blocked", value: 100000, suffix: "+", icon: <FaShieldAlt /> },
      { label: "Clients Secured", value: 200, suffix: "+", icon: <FaBuilding /> },
      { label: "Uptime", value: 99.99, suffix: "%", icon: <FaClock /> },
      { label: "Compliance Met", value: 50, suffix: "+", icon: <FaStar /> },
    ],
    features: ["Threat Monitoring", "Penetration Testing", "Incident Response", "Compliance Management", "Security Audits"],
    benefits: ["Enhanced Security Posture", "Regulatory Compliance", "Reduced Risk", "Business Continuity", "Customer Trust"],
  },
  {
    id: "social",
    title: "Social Networking",
    subtitle: "Connect your audience",
    icon: <FaUsers />,
    color: "#3B82F6",
    description: "Build powerful online communities and social networking platforms with modern engagement features and real-time interaction capabilities.",
    badge: "Community First",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Platforms Built", value: 85, suffix: "+", icon: <FaUsers /> },
      { label: "Active Users", value: 10, suffix: "M+", icon: <FaGlobeAmericas /> },
      { label: "Messages/Day", value: 1, suffix: "M+", icon: <FaBolt /> },
      { label: "Uptime", value: 99.9, suffix: "%", icon: <FaClock /> },
    ],
    features: ["User Profiles", "Real-Time Chat", "Media Sharing", "Groups & Communities", "Notifications"],
    benefits: ["Stronger User Engagement", "Community Building", "Increased Retention", "Real-Time Communication", "Network Growth"],
  },
  {
    id: "healthcare",
    title: "Healthcare & Fitness",
    subtitle: "Build wellness with tech",
    icon: <FaHeartbeat />,
    color: "#EC4899",
    description: "Technology-driven healthcare and fitness solutions that improve patient care, wellness management, and health outcomes through innovation.",
    badge: "HealthTech",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Patients Served", value: 100000, suffix: "+", icon: <FaHeartbeat /> },
      { label: "Clinics Connected", value: 500, suffix: "+", icon: <FaBuilding /> },
      { label: "Appointments", value: 50000, suffix: "+", icon: <FaCalendarAlt /> },
      { label: "Data Secured", value: 100, suffix: "TB+", icon: <FaShieldAlt /> },
    ],
    features: ["Appointment Scheduling", "Health Tracking", "Telemedicine", "Fitness Monitoring", "Patient Records"],
    benefits: ["Improved Patient Care", "Better Accessibility", "Efficient Management", "Health Insights", "Enhanced User Experience"],
  },
  {
    id: "event",
    title: "Event & Ticket",
    subtitle: "Manage your events seamlessly",
    icon: <FaCalendarAlt />,
    color: "#10B981",
    description: "Complete event management solutions for planning, promotion, ticketing, and attendee engagement with real-time analytics.",
    badge: "Event Pro",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Events Managed", value: 1500, suffix: "+", icon: <FaCalendarAlt /> },
      { label: "Tickets Sold", value: 500000, suffix: "+", icon: <FaTicketAlt /> },
      { label: "Attendees", value: 200000, suffix: "+", icon: <FaUsers /> },
      { label: "Satisfaction", value: 97, suffix: "%", icon: <FaStar /> },
    ],
    features: ["Online Registration", "Ticket Booking", "Event Scheduling", "QR Verification", "Analytics Dashboard"],
    benefits: ["Simplified Event Management", "Improved Attendance", "Automated Ticketing", "Real-Time Monitoring", "Better User Experience"],
  },
  {
    id: "food",
    title: "Food & Beverage",
    subtitle: "Digitizing dining experiences",
    icon: <FaUtensils />,
    color: "#F97316",
    description: "Technology solutions for restaurants, cafes, and food businesses to improve customer experience, streamline operations, and boost revenue.",
    badge: "FoodTech",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Restaurants Served", value: 450, suffix: "+", icon: <FaUtensils /> },
      { label: "Orders Processed", value: 2, suffix: "M+", icon: <FaBolt /> },
      { label: "Cities Covered", value: 30, suffix: "+", icon: <FaGlobeAmericas /> },
      { label: "Avg. Rating", value: 4.8, suffix: "/5", icon: <FaStar /> },
    ],
    features: ["Online Ordering", "Table Reservation", "Menu Management", "Delivery Tracking", "Customer Feedback"],
    benefits: ["Increased Orders", "Faster Service", "Improved Customer Satisfaction", "Operational Efficiency", "Revenue Growth"],
  },
  {
    id: "ticketing",
    title: "Ticketing & Booking",
    subtitle: "Power travel and leisure",
    icon: <FaTicketAlt />,
    color: "#06B6D4",
    description: "Advanced booking and reservation platforms for travel, hospitality, and entertainment businesses with seamless payment integration.",
    badge: "TravelTech",
    services: [
      { name: "Web Development", icon: <FaCode /> },
      { name: "Mobile Apps", icon: <FaMobileAlt /> },
      { name: "AI Solutions", icon: <FaBrain /> },
      { name: "Cloud Infrastructure", icon: <FaCloud /> },
      { name: "UI/UX Design", icon: <FaPenFancy /> },
      { name: "Automation", icon: <FaCogs /> },
    ],
    stats: [
      { label: "Bookings/yr", value: 500000, suffix: "+", icon: <FaTicketAlt /> },
      { label: "Partners", value: 800, suffix: "+", icon: <FaUsers /> },
      { label: "Destinations", value: 100, suffix: "+", icon: <FaGlobeAmericas /> },
      { label: "Revenue", value: 100, suffix: "Cr+", icon: <FaChartLine /> },
    ],
    features: ["Online Reservations", "Payment Integration", "Booking Management", "Customer Accounts", "Reporting Tools"],
    benefits: ["Easy Booking Process", "Higher Customer Satisfaction", "Automated Operations", "Increased Revenue", "Better Resource Utilization"],
  },
];
